# Generated by Django 3.2.6 on 2022-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('OutDate', models.DateField()),
                ('InDate', models.DateField()),
                ('UserName', models.CharField(max_length=50, unique=True)),
                ('MobNo', models.IntegerField()),
            ],
        ),
    ]
