# Generated by Django 3.2.6 on 2022-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='MobNo',
            field=models.BigIntegerField(),
        ),
    ]
